---
dependency:
  name: 'galaxy'
driver:
  name: 'docker'
lint:
  name: 'yamllint'
platforms:
  - name: "${MOLECULE_DISTRO:-debian9}"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian9}-ansible:latest"
    command: '/lib/systemd/systemd'
    pre_build_image: True
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: True
provisioner:
  name: 'ansible'
  lint:
    name: 'ansible-lint'
verifier:
  name: 'testinfra'
  lint:
    name: 'flake8'
